name: "CI - JDK 11 Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-jdk11:
    name: "JDK 11 Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java using binaries from AdoptOpenJDK
        uses: cescoffier/setup-jdk@v1.1.3

        with:
          java-version: openjdk11
      - name: Build
        run: mvn clean package

