name: "CI - JDK 11 Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-jdk11:
    name: "JDK 11 Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup AdoptOpenJDK
        uses: joschi/setup-jdk@v2.2.0
        with:
          java-version: 11
      - name: Build
        run: mvn clean package -e

